<a href="https://colab.research.google.com/github/Uttam1618/mygoldenpie/blob/main/Numpy_Sheets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
# To import the numpy library
import numpy as np


In [ ]:
# To create one dimensional Array

# To create array from a list
li = [1,2,3,5]
print(np.array(li))

# From tuple
tup = (3, 5, 6, 7, 8)
print(np.array(tup))

# Using fromiter() to create an array
'''(👉 It builds a NumPy array directly from an iterable without making an intermediate list.)'''

iterable = (a for a in range(8))
print(np.fromiter(iterable, float))

iterable = (x**2 for x in range(10))
result = np.fromiter(iterable, dtype=int)
print(result)

gen = (x for x in range(100))
arr = np.fromiter(gen, dtype=int, count=5)
print(arr)

In [31]:
# Creating multi dimensional array
#(They are stored in a tabular form that is in the form of rows and columns)

# From list
list_1= [1, 2, 4, 5]
list_2= [3, 5, 6, 8]
list_3= [55, 65, 66, 35]
print(np.array([list_1, list_2, list_3]))

# Using numpy.empty()
print(np.empty([4,3], dtype=int))

[[ 1  2  4  5]
 [ 3  5  6  8]
 [55 65 66 35]]
[[ 1  2  4]
 [ 5  3  5]
 [ 6  8 55]
 [65 66 35]]


In [ ]:
# INITIAL PLACEHOLDERS

# For 1D numpy array
# To create numpy array using np.arange()
print(np.arange(1,10))

# using np.linspace()
(It is used to create an array of evenly spaced numbers over a specified interval.)

arr = np.linspace(0, 10, 5) # by default endpoint will be included which is 10
print(arr)

print(np.linspace(0, 10, 5, endpoint=False) # doesnot include 10

print(np.linspace(0,10)) # the default number of values is 50

# Using np.zeros()
(creates an array filled entirely with zeros)

print(np.zeros(shape, dtype, order) # order is memory layout C or F, looks same but memory layout is different

print(np.zeros(5, dtype= int)

# using np.ones()
(creates new array filled entirely with one)

np.ones(shape, dtype, order)
print(np.ones(5))
print(np.ones(5, dtypes=int))
print(np.ones(5, dtype=int, order='C'))

#using np.random.rand()
(generates an array of random numbers drawn from a uniform distribution over the interval [0,1] means every number is between 0(inclusive) and 1(exclusive), and each has equal chance of appearing.)

print(np.random.rand()) # if no argument given, then output will be a single random number

print(np.random.rand(5)) # 1D array

print(np.random.rand(2,3)) # 2D array, 2 rows and 3 columns

# Using np.random.randint()
(generates random integer from specified range)

print(np.random.randint(low, high=none, size=none, dtype=int))
print(np.random.randint(10)) # lowest integer is 10, means it gives the random integer between 0 to 9
print(np.rando.randint(10, 50, size=10)
print(np.random.randint(10, 50, size=(5, 6)))

In [ ]:
# for n dimensional numpy array
# Using np.zeros()
print(np.zeros([4,3], dtype = int))

# using np.ones()
print(np.zeros([4,3], dtype = int))

# using np.full()
np.full(shape, fill_value, dtype=None, order='C', *, like=None)
print(np.full(5, 7))
print(np.full([5,7], 9, dtype = int))

# using np.eye()
'''(generates indentity matrix)
(generate rectangular version if you specify rows and column separately)'''

numpy.eye(N, M=None, k=0, dtype=float, order='C')
print(np.eye(2)) # generate 2x2 identity matrix
print(np.eye(3,4, k=1)) # generate 3x4 matrix, diagonal shifted above
print(np.eye(3, 4, k=-1)) # generate 3x4 matric, diagonal shifted below

**Inspecting Properties**


For 1D numpy array

In [ ]:
arr = np.asarray([1, 2, 3, 4])
# check size of the array
print("Size:", arr.size)

# check len of the array
print("len:", len(arr))

# check shape of the array
print("Shape:", arr.shape)

# check dtype of the array elements
print("Datatype:", arr.dtype)

# change the dtype to 'float64'
arr = arr.astype('float64')
print(arr)
print("Datatype:", arr.dtype)

# convert array to list
lis = arr.tolist()
print("\nList:", lis)
print(type(lis))

For n dimensional numpy array

In [ ]:
# Two dimensional numpy array
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
arr = np.array([list_1, list_2, list_3])

# check size of the array
print("Size:", arr.size)

# check length of the array
print("Length:", len(arr))

# check shape of the array
print("Shape:", arr.shape)

# check dtype of the array elements
print("Datatype:", arr.dtype)

# change the dtype to 'float64'
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

# convert array to list
lis = arr.tolist()
print("\nList:", lis)
print(type(lis))

**Getting infromation on a numpy function**

In [ ]:
# get info about the python function
np.info(np.eye)
help(np.eye) # python built in function

# get info about the numpy constant or class
np.info(np.ndarray) ''' All arrays you create with functions like np.array(),
np.zeros(), np.eye(), etc., are actually instances of numpy.ndarray.'''

**Saving and loading files**

In [ ]:
# to save the file
np.save("newfile', np.arrange(5))

# to load the file
print(np.load("newfile.npy"))

# to save the file in a text fie, use savetxt()
x = np.arange(0,10,1)
print(x)
c = np.savetxt("newfile.txt", x, delimiter = ', ')

# to load from the text file, loadtxt()
d = np.loadtxt("newfile.txt")
print(d)

# to load CSV file in python using numpy, use genfromtxt() function,
Data = np.genfromtxt("files\myfile.csv", delimiter=",")
print(Data)

**Sorting Array**

In [ ]:
# for one dimensional array
random = np.array([34, 55, 98, 76, 90, 23, 66, 12, 3])
random.sort()
print(random)

import numpy as np
array_2d = np.array([[5, 2, 8],
                     [1, 9, 4],
                     [7, 3, 6]])

print("Original array:")
display(array_2d)

# Sort along axis=0 (columns) - sorts each column independently
sorted_axis_0 = np.sort(array_2d, axis=0) # Using np.sort to return a new array
print("\nSorted along axis=0 (columns):")
display(sorted_axis_0)

# Sort along axis=1 (rows) - sorts each row independently
sorted_axis_1 = np.sort(array_2d, axis=1) # Using np.sort to return a new array
print("\nSorted along axis=1 (rows):")
display(sorted_axis_1)

# Sort the flattened array (axis=None)
sorted_flattened = np.sort(array_2d, axis=None) # Using np.sort to return a new array
print("\nSorted flattened array (axis=None):")
display(sorted_flattened)

**Numpy array manipulation**

In [ ]:
# for one dimensional array
# adding the value at the end
arr = np.array([1, 2, 3 ,4])
arr = np.append(arr, [7])
print(arr)

# for n dimensional array
# Adding the values at the end
# of a numpy array
arr = np.arange(1, 13).reshape(2, 6)
print("Original Array")
print(arr, "\n")

# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
arr_col = np.append(arr, col, axis=0)
print("Array after appending the values column wise")
print(arr_col, "\n")

# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
arr_row = np.append(arr, row, axis=1)
print("Array after appending the values row wise")
print(arr_row)